- name: installing nginx
  ansible.builtin.dnf:
    name: nginx
    state:  latest

- name: start and enable nginx
  ansible.builtin.service:
    name: nginx
    state:  started
    enabled:  yes

- name: import role tasks 
  ansible.builtin.import_role:
    name: common
    tasks_from: main

- name: copying expense config file to web server
  ansible.builtin.template:
    src:  expense.conf.j2
    dest: /etc/nginx/default.d/expense.conf
  notify: 
    - restart nginx


